### ISSUE TITLE
Color picker tool extension

### ISSUE THREAD

**Issue by yosaami** [Coders-Dorm/Best-Of-Chrome-Extensions#12]
I want to create a color picker tool extension that can pick any color from the web page and can also give it's hexcode.

**Comment by kodepirate** [comment]
Go for it @yosaami

**Comment by yosaami** [comment]
you have assigned yourself, please assign me.

**Comment by kodepirate** [comment]
haha😅😅

**Comment by yosaami** [comment]
hey, you didn't merge the PR?
