### ISSUE TITLE
Jokes Cracker extension

### ISSUE THREAD

**Issue by ChandanP007** [Coders-Dorm/Best-Of-Chrome-Extensions#17]
I want to add a random jokes generator extension.
Can I ?

**Comment by kodepirate** [comment]
What's this dude?🙂 @ChandanP007

**Comment by ChandanP007** [comment]
![image](https://user-images.githubusercontent.com/95927947/195114084-b124be1d-2fe4-4167-b78e-5ac73948f303.png)

**Comment by ChandanP007** [comment]
simple random jokes .. nothing much 🙂

**Comment by ChandanP007** [comment]
Thanks
