### ISSUE TITLE
Browsing Time Tracker

### ISSUE THREAD

**Issue by gagan-gv** [Coders-Dorm/Best-Of-Chrome-Extensions#18]
It tracks total time someone has used the browser and closes the browser after the timer ends. Hacktoberfest

**Comment by kodepirate** [comment]
@gagan-gv Assigned

**Comment by Morbius00** [comment]
hey any one up for the issue can do it...

**Comment by kodepirate** [comment]
Are you working in this issue @gagan-gv 
Please inform

**Comment by gagan-gv** [comment]
@kodepirate trying it, but not able to get anywhere near it.

**Comment by kodepirate** [comment]
Wanna transfer it?
Or wanna work on it! @gagan-gv

**Comment by gagan-gv** [comment]
There is no major progress, it's better to close it.
