### ISSUE TITLE
Image to text generator

### ISSUE THREAD

**Issue by vcaiii** [Coders-Dorm/Best-Of-Chrome-Extensions#26]
Any interest in text recognition in images? If so, I'd like to be assigned for hacktoberfest.

**Comment by Morbius00** [comment]
> Any interest in text recognition in images? If so, I'd like to be assigned for hacktoberfest.

please describe a little about it how the extension works

**Comment by kodepirate** [comment]
Sounds good,
Go for it 
Assigned you @vcaiii

**Comment by vcaiii** [comment]
> > Any interest in text recognition in images? If so, I'd like to be assigned for hacktoberfest.
> 
> please describe a little about it how the extension works

Sure thing, I will add a description to the pull request.
