### ISSUE TITLE
Google meet chatbox participants attendance.

### ISSUE THREAD

**Issue by bunnykek** [Coders-Dorm/Best-Of-Chrome-Extensions#36]
Will export a txt file containing all the names of the users who has participated in the chatbox discussion.

**Comment by kodepirate** [comment]
Is it even an extension? @bunnykek

**Comment by kodepirate** [comment]
Like all the participant list? @bunnykek

**Comment by bunnykek** [comment]
> Like all the participant list? @bunnykek

yes
