### ISSUE TITLE
Zoom attendance exporter

### ISSUE THREAD

**Issue by bunnykek** [Coders-Dorm/Best-Of-Chrome-Extensions#37]
Will export all the participants names into a text file.

**Comment by kodepirate** [comment]
Is there any difference from the other issues you created! @bunnykek

**Comment by kodepirate** [comment]
Elaborate please @bunnykek

**Comment by bunnykek** [comment]
https://github.com/Coders-Dorm/Best-Of-Chrome-Extensions/issues/36#issuecomment-1276504414
but for zoom meet.

Suppose a teacher wants the attendance at a particular instance then he can just click on extension logo to export the list of students at that particular instance.

**Comment by kodepirate** [comment]
What are you going to do about this? @bunnykek

**Comment by bunnykek** [comment]
what? I will be making two extensions, one for Zoom and other for Gmeet. Should I combine both into one? It would be possible but my main motive is to get 4 pull requests merged lol.

**Comment by bunnykek** [comment]
> 

Yeah, I understand. I Will come up with some new idea.

**Comment by kodepirate** [comment]
Sounds good, thanks for your understanding buddy @bunnykek
