### ISSUE TITLE
JioSaavn CDN URL generator

### ISSUE THREAD

**Issue by bunnykek** [Coders-Dorm/Best-Of-Chrome-Extensions#38]
An extension to get the direct download CDN link of the currently playing song in jiosaavn.com
Demo video:
https://user-images.githubusercontent.com/67633271/195443594-b596743e-e980-405b-a7bb-53c5c37862b2.mp4

**Comment by kodepirate** [comment]
This looks great.. 
How about can you make it in Spotify version, as Spotify holds the market.
Is it possible? @bunnykek

**Comment by unclebinary1001** [comment]
@bunnykek Can I take this up.

**Comment by kodepirate** [comment]
Sure man, assigning you then @bunnykek

**Comment by unclebinary1001** [comment]
Hello, @bunnykek I would like to work on this or work on it together if you may need any help.

**Comment by bunnykek** [comment]
> This looks great.. 
> How about can you make it in Spotify version, as Spotify holds the market.
> Is it possible? @bunnykek 

Sorry, as the spotify has DRM so I won't be making any extension for it.

**Comment by kodepirate** [comment]
Ok @bunnykek assigned you

**Comment by bunnykek** [comment]
> Hello, @bunnykek I would like to work on this or work on it together if you may need any help. 
> 

Actually my extension is almost ready, thats why have made the demo.

**Comment by unclebinary1001** [comment]
Oh okay. Good luck with the remaining part.

**Comment by kodepirate** [comment]
merged @bunnykek
