### ISSUE TITLE
To-do List 

### ISSUE THREAD

**Issue by kodepirate** [Coders-Dorm/Best-Of-Chrome-Extensions#4]

**Comment by yosaami** [comment]
I have created the to-do list chrome extension using HTML, CSS and JavaScript
Please assign it to me under the hacktoberfest tag.
![Screenshot (28)](https://user-images.githubusercontent.com/76916269/195072512-bfa9e708-0a0e-46c9-a419-c2d6369470c9.png)

**Comment by kodepirate** [comment]
Is it working properly? @yosaami

**Comment by yosaami** [comment]
yes, it's working perfectly.

**Comment by kodepirate** [comment]
ok @yosaami

**Comment by Morbius00** [comment]
Completed
