### ISSUE TITLE
Dictionary Extension

### ISSUE THREAD

**Issue by VEDANGIBHUJANG** [Coders-Dorm/Best-Of-Chrome-Extensions#45]
Hey @kodepirate ,
I want to create a dictionary extension for chrome please assign this issue to me.
Thank you!

**Comment by VEDANGIBHUJANG** [comment]
We can search meanings of different words using it.

**Comment by kodepirate** [comment]
ok do it @VEDANGIBHUJANG

**Comment by VEDANGIBHUJANG** [comment]
Thank you! 😃

**Comment by kodepirate** [comment]
Merged @VEDANGIBHUJANG
