### ISSUE TITLE
Create a website toggle extension 

### ISSUE THREAD

**Issue by Koustavjr** [Coders-Dorm/Best-Of-Chrome-Extensions#48]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
This extension will allow user to toggle between blocking and unblocking a list of website URLs.

**Describe alternatives you've considered**

**Additional context**

**Comment by Koustavjr** [comment]
@kodepirate @Morbius00  can u please assign me this issue.

**Comment by Morbius00** [comment]
Assigned go for it

**Comment by kodepirate** [comment]
Merged
