### ISSUE TITLE
Creating a Chrome Extension

### ISSUE THREAD

**Issue by amitkroutthedev** [Coders-Dorm/Best-Of-Chrome-Extensions#49]
**Is your feature request related to a problem? Please describe.**
Many times users log details to their info to a phished site for which they face problems.

**Describe the solution you'd like**
Creating a chrome extension which can check if a current url is phish or legitimate

**Describe alternatives you've considered**

**Additional context**
Created a backend REST API to check if the url is legitmate of phished.

**Comment by amitkroutthedev** [comment]
@kodepirate @Morbius00 can u please assign me this issue.

**Comment by Morbius00** [comment]
Sounds good go for it.....
Assigned

**Comment by amitkroutthedev** [comment]
Created a pull request

**Comment by kodepirate** [comment]
Merged @amitkroutthedev
