### ISSUE TITLE
Website Blocker / Parentel Control Extension

### ISSUE THREAD

**Issue by adityaaggarwal12** [Coders-Dorm/Best-Of-Chrome-Extensions#67]
block any website with this extension

**Comment by adityaaggarwal12** [comment]
Please Assing for Hacktoberfest

**Comment by kodepirate** [comment]
What are you using in this project?
Can you please elaborate @adityaaggarwal12

**Comment by adityaaggarwal12** [comment]
> What are you using in this project?
> Can you please elaborate @adityaaggarwal12 

Made extension with html css and js 

And used declarative net request, local storage chrome permissions  to block websites

**Comment by Morbius00** [comment]
assigned go for it
