### ISSUE TITLE
Prankster extension

### ISSUE THREAD

**Issue by RidhamRj** [Coders-Dorm/Best-Of-Chrome-Extensions#69]
By activating this extension you  can prank your friends 

This extension automatically changes all the web results after it is activated

No big deal to resolve it
Just deactivate extension

**Comment by RidhamRj** [comment]
@Morbius00 @kodepirate kindly review

**Comment by RidhamRj** [comment]
@kodepirate @Morbius00 ...
May I work on pr?

**Comment by Morbius00** [comment]
well is  it a useful extension , I don't think so ..
still I am assignees you go for it

**Comment by kodepirate** [comment]
You have done a great job mam
The extension is quite interesting.
Keep Contributing 🤗 @RidhamRj
